### PR TITLE
Update Registration Page AB#10735

### PR DESCRIPTION
**Pull request by tiagograf-AOT**
# Fixes or Implements [AB#10735](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/10735)

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

UI Updates to Registration page.
Text update to "incomplete profile" banner.

image
image

image

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES | NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

### CODE REVIEW

**Review by sslaws — DISMISSED** [review]

**Comment by ninosamson** [comment]
@tiagograf-AOT Can you please remove the period after "I agree to the terms of service above"?

**Comment by ninosamson** [comment]
@tiagograf-AOT Replace "Used for" with "Receive" for both inputs

**Review by ninosamson — CHANGES_REQUESTED** [review]
See my comments (x2)

**Review by ninosamson — CHANGES_REQUESTED** [review]
What about the period when accepting "terms of service"

**Review by ninosamson — APPROVED** [review]
Thanks @tiagograf-AOT

**Review by sslaws — APPROVED** [review]

**Pull request merged**
