### PR TITLE
Update date format AB#10251

### PR DESCRIPTION
**Pull request by tiagograf-AOT**
# Fixes or Implements [AB#10251](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/10251)

* [ ] Enhancement
* [ ] Bug
* [ ] Documentation

## Description

Update date formats throughout the app.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

* [ ] Unit Tests Updated
* [ ] Functional Tests Updated
* [x] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES | NO

### Browsers Tested

* [ ] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant.  Include any specialized deployment steps here.

### CODE REVIEW

**Review by leobcgov — APPROVED** [review]

**Review by leobcgov — CHANGES_REQUESTED** [review]
Date Filters seem to be broken. Previously entering filter "2020-06-14" for the start date and "2020-06-14" for the end date returns 2 timeline entries. Now it returns 0 entries.

**Comment by leobcgov** [comment]
> i just tested it and it worked, can you elaborate?
> image

It is interesting. I have just pulled the 10251 again and it doesn't work for me. May be timezone issue?
image

**Comment by tiagograf-AOT** [comment]
I removed the time from the date object, can you try again? @leobcgov

**Comment by tiagograf-AOT** [comment]
I updated the filter tests and they all seem to work now.

**Review by leobcgov — APPROVED** [review]

**Comment by leobcgov** [comment]
It works for me now, thanks @tiagograf-AOT

**Review by FuriousLlama — APPROVED** [review]

**Review by FuriousLlama — APPROVED** [review]

**Pull request merged**
