### PR TITLE
Rearrange functional tests AB#10996 #10995 #10994

### PR DESCRIPTION
**Pull request by pagustinqt20**
# Rearrange functional tests [AB#10996](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/10996)  [AB#10995](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/10995)  [AB#10994](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/10994)

## Description

This PR includes tasks 10994,10995 & 10996.

As a Health Gateway team, we need a mock environment that we can connect to that has standardized data so that we can demo and test UI functionality independent of external partners. 

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [x] Functional Tests Updated
-   [ ] Not Required

### UI Changes

YES | NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Results of manual run locally (Mock)
**Task 10996**
image

**Task 10995**
image
image
image

**Task 10994**
image

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

### CODE REVIEW

**Review by MikeLyttle — COMMENTED** [review]
See my comments on the Jira task.  This looks like a good starting point, but additional changes may be required.

**Review by sslaws — APPROVED** [review]

**Review by MikeLyttle — CHANGES_REQUESTED** [review]
Some of the tests mentioned in the tasks don't seem to be included in the move/copy to ui/mock:

- resourceCentre/
  - resourceCentre
- services/
  - webClient/
    - comment
    - note
    - userFeedback
    - userProfile (notificationsettings)
    - webClient
- timeline/
  - notes (mock)

**Comment by pagustinqt20** [comment]
@MikeLyttle  As discussed those tests that are not calling external services are clone in mock folder. Updated the description. But will create a summary (Combinations of all tickets - will update the story 10487)

**Review by MikeLyttle — CHANGES_REQUESTED** [review]
Looks good, but some still seem to be missing:

- services/
  - webClient/
    - dependent (patient)
- timeline/
  - notes (mock)
- user/
  - dependents (patient)
  - feedback
  - starRating

**Review by MikeLyttle — APPROVED** [review]

**Review by BrianMaki — APPROVED** [review]

**Pull request merged**
