### PR TITLE
Updated the nav footer

### PR DESCRIPTION
**Pull request by leobcgov**
# Fixes or Implements [AB#9081](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/9081)

* [X] Enhancement
* [ ] Bug
* [ ] Documentation

## Description
- Updated nav footer

## Testing

* [ ] Unit Tests Updated
* [ ] Functional Tests Updated
* [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES

### Browsers Tested

* [X] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant.  Include any specialized deployment steps here.  

</br>
</br>
</br>
___
  
## Reviewer Guidelines

A reviewer should examine the PR if the Status above indicates the PR is **Ready**.
Once ready, the reviewer should read the information below as well as supporting information like the Azure ticket to ensure they have a good understanding of the request.

The reviewer should then:

1. Is the PR template complete and accurate?

    Confirm by reading all sections below.

1. Confirm the merge branch

    A normal feature/bug branch should merge into the Dev branch.  Exceptions for hotfix and sprint merges do occur and the target would then be Master.

1. Do the code commits have an appropriate comment and include linkage to the azure ticket by including a reference to "AB#nnnn"?

1. Review the Code Changes

    1. Do the changes match the description?

        The code commits should reflect the documented description and nothing more.  If additional changes are included the reviewer should call these out and request that the developer document the changes in Azure and in the description or remove the changed code.

    1. useful tips

        * Any obvious errors or omissions?
        * Does the code match the style of other similar work?
        * Is the code easy to understand?
        * Is the code well documented?
        * DB Migrations are appropriate?

If the Answer to any of the questions above is No, then a request for change should be the result of the review.

### CODE REVIEW

**Comment by FuriousLlama** [comment]
Check with Niño to see if the old footer ones need to remain

**Comment by ninosamson** [comment]
@leobcgov We need to remove the old ones, per user story. 
Only these ones should remain: 
Terms of Service 
Release Notes 
Contact Us 
About Us

**Comment by leobcgov** [comment]
> @leobcgov We need to remove the old ones, per user story.
> Only these ones should remain:
> Terms of Service
> Release Notes
> Contact Us
> About Us

Thanks @ninosamson! I have updated the footer as follows:
image

**Review by FuriousLlama — APPROVED** [review]

**Comment by tiagograf-AOT** [comment]
you need to update your npm packages, and run lint again, it will remove the ";" from the style attributes

**Review by tiagograf-AOT — CHANGES_REQUESTED** [review]
update packages and lint

**Comment by leobcgov** [comment]
build has been fixed now for this PR

**Review by tiagograf-AOT — DISMISSED** [review]

**Review by FuriousLlama — APPROVED** [review]

**Review by tiagograf-AOT — DISMISSED** [review]

**Review by sam-warren — APPROVED** [review]

**Review by tiagograf-AOT — APPROVED** [review]

**Pull request merged**
