### PR TITLE
Sort Functional Tests AB#11764

### PR DESCRIPTION
**Pull request by pagustinqt20**
# Sort Functional Tests [AB#11764](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/11764)

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

Add functional tests for sorting all record types.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [x] Functional Tests Updated
-   [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

### CODE REVIEW

**Comment by BrianMaki** [comment]
Have the tests been run locally against Dev using ‘npx cypress run’? Using ‘cypress run’ is more indicative of how the tests run in the pipeline than using ‘npx cypress open’.

You can individual tests via ‘cypress run’ as well. Example: npx cypress run --spec "cypress/integration/my-spec.js"

After merging code, make sure you run the pipeline in Axure for Cypress Parallel Tests.

**Comment by pagustinqt20** [comment]
@BrianMaki  Noted. I run the test pointed in my local. The one we have issue "uncaught" it passed locally but it only shows when the developer tool is open. I think that one needs to be investigated why  it pass locally but not when we push in dev.

**Comment by BrianMaki** [comment]
> @BrianMaki Noted. I run the test pointed in my local. The one we have issue "uncaught" it passed locally but it only shows when the developer tool is open. But when the developer tools is closed it will show the error.
> 
> image

@pagustinqt20 you are using ‘npx cypress open’  in your example. I suggested using ‘npx cypress run’ to run all tests or ‘npx cypress run --spec "cypress/integration/my-spec.js"‘. If you don’t want to do it, then make sure run sure run the pipeline test.

**Comment by pagustinqt20** [comment]
@BrianMaki  Yes I use "npx cypress open". Noted I will try "npx cypress run"

**Comment by BrianMaki** [comment]
> @BrianMaki Yes I use "npx cypress open". It is in the readme instruction. Noted I will try "npx cypress run".
> image
@pagustinqt20  I don’t think it’s in the README. The pipeline and release on Azure uses cypress run.  To ensure everything is run the same. You should run cypress run locally periodically. Sometimes you get errors on dev but not locally. Also it’s best to test against dev for a variety of reasons including speed. I can explain more on Monday.

**Review by sslaws — APPROVED** [review]

**Review by BrianMaki — APPROVED** [review]

**Review by BrianMaki — APPROVED** [review]

**Pull request merged**
