### PR TITLE
Popover Tutorial: Export Records

### PR DESCRIPTION
**Pull request by leobcgov**
# Fixes or Implements [AB#9841](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/9841)

* [X] Enhancement
* [ ] Bug
* [ ] Documentation

## Description
- Implemented Popover tutorial for Export Records
- Removed Print button from menu (sub menu)
- Add functional tests

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

* [ ] Unit Tests Updated
* [X] Functional Tests Updated
* [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES

### Browsers Tested

* [X] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant.  Include any specialized deployment steps here.

### CODE REVIEW

**Review by FuriousLlama — APPROVED** [review]

**Comment by FuriousLlama** [comment]
PR comment: the title is misleading, this is removing the printing

**Comment by ninosamson** [comment]
@leobcgov Can you please ensure the copy is as below? Just making sure as it is different on the mock-up: 
"Download a pdf of your records. e.g. COVID-19 test proof for employers."

**Review by sslaws — APPROVED** [review]

**Review by tiagograf-AOT — APPROVED** [review]

**Comment by leobcgov** [comment]
@FuriousLlama can you take a look to make sure as you are the code owner?

**Comment by leobcgov** [comment]
> PR comment: the title is misleading, this is removing the printing
This PR is for the whole user story https://qslvic.visualstudio.com/Health%20Gateway/_workitems/edit/9841
which include adding popover for Export Records and also removing the printing

**Review by FuriousLlama — APPROVED** [review]

**Pull request merged**
