### PR TITLE
Features/7561

### PR DESCRIPTION
**Pull request by sslaws**
Implements [AB#7561](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/7561)

Parsing of Provincial PharmaCare drug file, we're waiting on a few answers for additional fields that are in the file but not documented and also some field length questions.

The main app BCDrugProvApp is not part of this ticket and will be refined further in [AB#7562](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/7562)

I've raised bug [AB#7588](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/7588) to eliminate the use of Project Guids.

### CODE REVIEW

**Comment by healthgatewaybc** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=commonlibrary_pr_166

**Comment by healthgatewaybc** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=commonlibrary_pr_166

**Comment by healthgatewaybc** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=commonlibrary_pr_166

**Comment by healthgatewaybc** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=patientservice_pr_166

**Comment by healthgatewaybc** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=webclient_pr_166

**Comment by sslaws** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=immunization_pr_166

**Comment by sslaws** [comment]
SonarQube Report: https://sonarqube-gateway.pathfinder.gov.bc.ca/dashboard?id=Medicationservice_pr_166

**Pull request merged**
