### PR TITLE
Add disclaimer to timeline filter for AB #13975

### PR DESCRIPTION
**Pull request by BrianMaki**
# Implements [AB#13975](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/13975)

## Description

1. Add disclaimer to timeline filter - disclaimer only displays when Immunization filter is selected.
2. Updated div id for dependent immunization.

## Testing

- [ ] Unit Tests Updated
- [ ] Functional Tests Updated
- [x] Not Required

## UI Changes

**Timeline with Immunization filter:**

Screen Shot 2022-09-26 at 6 30 19 PM

**Timeline with all filters except Immunization:**

Screen Shot 2022-09-26 at 6 30 33 PM

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

### CODE REVIEW

**Review by sslaws — DISMISSED** [review]

**Review by mk08sh — CHANGES_REQUESTED** [review]
- Disclaimer should not be shown when immunization filter is not applied.

**Comment by BrianMaki** [comment]
> * Disclaimer should not be shown when immunization filter is not applied.

**Comment by BrianMaki** [comment]
> * Disclaimer should not be shown when immunization filter is not applied.
When no filter is applied all results are returned, which includes Immunizations.  In this situation, you do not want the disclaimer to be shown?

**Comment by BrianMaki** [comment]
> * Disclaimer should not be shown when immunization filter is not applied.
Disclaimer should not be shown when immunization filter is not applied.
When no filter is applied all results are returned, which includes Immunizations. In this situation, you do not want the disclaimer to be shown?

**Comment by BrianMaki** [comment]
> * Disclaimer should not be shown when immunization filter is not applied.

Fixed with latest commit.

**Review by sslaws — APPROVED** [review]

**Review by rayking29 — APPROVED** [review]

**Pull request merged**
