### PR TITLE
Bootstrap grid system for landing page buttons

### PR DESCRIPTION
**Pull request by FuriousLlama**
# Fixes or Implements [AB#8822](https://qslvic.visualstudio.com/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/8822)

* [x] Enhancement
* [ ] Bug
* [ ] Documentation

## Description

Removed the media queries for individual buttons. Cleaned a double iteration with icons and labels

## Testing

* [ ] Unit Tests Updated
* [ ] Functional Tests Updated
* [x] Not Required

image

image

image

### CODE REVIEW

**Comment by FuriousLlama** [comment]
Good catch! I have updated the code to work better with wide screens

**Comment by leobcgov** [comment]
With the latest code I'm still seeing the Log in button on the right side of the text column as follows, mbe review with @ninosamson to make sure
image

**Comment by leobcgov** [comment]
> With the latest code I'm still seeing the Log in button on the right side of the text column as follows, mbe review with @ninosamson to make sure. For info, my screen wide is 1920.
> image

@FuriousLlama sorry, please ignore this, issue with my last code pull. It is showing nicely now.

**Comment by leobcgov** [comment]
I have approved too fast :-)
I have noticed that the space between device image and text/buttons becomes bigger and bigger for the larger screen. This doesn't look nice even for a standard 1920 screen. Mbe creating a bug to address this?
image

**Pull request merged**
